// Package db provides the data access layer for the appointments service.
// It wraps a PostgreSQL database using [database/sql] and exposes type-safe
// query methods generated by sqlc.
//
// # Architecture
//
// The package is built around three layers:
//
//   - Connection management ([New], [Config], [database]) — opens and
//     configures the connection pool, returns a [Database] handle.
//   - Replica ([Replica]) — a thin wrapper around [*sql.DB] that implements
//     the [DBTX] interface and exposes [Replica.Begin] for transactions.
//   - Query layer ([Query], [Querier]) — a stateless [Queries] value whose
//     methods accept a [DBTX] so they work transparently against a plain
//     connection or an active transaction.
//
// # Basic Usage
//
// Initialize the database once at application startup:
//
//	database, err := db.New(db.Config{
//	    PrimaryDSN: os.Getenv("DATABASE_URL"),
//	    Namespace:  "appointments",
//	})
//	if err != nil {
//	    log.Fatal(err)
//	}
//	defer database.Close()
//
// Run a query against the primary replica:
//
//	tenant, err := db.Query.FindTenantByID(ctx, database.RO(), tenantID)
//
// Run multiple queries inside a transaction:
//
//	tx, err := database.RW().Begin(ctx)
//	if err != nil {
//	    return err
//	}
//	defer tx.Rollback()
//
//	if err := db.Query.InsertTenant(ctx, tx, params); err != nil {
//	    return err
//	}
//	if err := db.Query.InsertStatusHistory(ctx, tx, historyParams); err != nil {
//	    return err
//	}
//	return tx.Commit()
//
// # Key Features
//
//   - Type-safe queries: all SQL operations are generated by sqlc v1.30.0
//     from files in the queries/ directory. Never edit *_generated.go files
//     by hand; run go generate ./pkg/db/... to regenerate them.
//
//   - Connection pooling: [New] configures the pool with sensible defaults
//     (25 max open connections, 10 idle, 5-minute lifetime) to avoid
//     cold-start latency.
//
//   - Unified DBTX interface: [DBTX] is satisfied by both [*Replica] and
//     [*sql.Tx], so every query method accepts either without branching.
//
//   - Transaction support: [Replica.Begin] starts a [DBTx] that adds
//     [DBTx.Commit] and [DBTx.Rollback] on top of [DBTX].
package db
